version: '3.4'

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      DATABASE_NAME: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./mysql/backup/files/:/data_backup/data
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer    
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 8080:8080

  nodeblog:
    image: nodeblog
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      NODE_ENV: development
      HOST: $MYSQL_HOST
      MYSQL_LOCAL_PORT: $MYSQL_LOCAL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysqldb

volumes: 
  db-config:
  db-data:
